### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by overload08** [overload08/domogik-plugin-hue#1]
Traceback (most recent call last):
  File "/var/lib/domogik//domogik_packages/plugin_hue/bin/hue.py", line 140, in <module>
    tts = HueManager()
  File "/var/lib/domogik//domogik_packages/plugin_hue/bin/hue.py", line 65, in __init__
    status = b.get_light(self.device_list[device_id]['address'],'on')
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 855, in get_light
    return state['state'][parameter]
TypeError: list indices must be integers, not str

**Comment by overload08** [comment]
Appear when bridge is not connected
TODO : exception on connect
