### ISSUE TITLE
Right problem

### ISSUE THREAD

**Issue by overload08** [overload08/domogik-plugin-hue#4]
2017-01-14 20:22:09,827 domogik-hue DEBUG Send client status : starting
2017-01-14 20:22:24,828 domogik-hue DEBUG Send client status : starting
2017-01-14 20:22:39,669 domogik-hue DEBUG Process informations|python_version=2.7|psutil_version=2.1.1|domogik_version=0.5.1|component=plugin-hue|component_version=1.0|pid=3314|cpu_percent_usage=0.2|memory_total=3693.0|memory_percent_usage=0.5|memory_rss=19.0|memory_vsz=402.0|num_threads=5|num_file_descriptors_used=19|platform=x86_64|num_core=2|git_branch=|git_revision=
2017-01-14 20:22:39,829 domogik-hue DEBUG Send client status : starting
2017-01-14 20:22:54,830 domogik-hue DEBUG Send client status : starting
2017-01-14 20:23:09,832 domogik-hue DEBUG Send client status : starting
2017-01-14 20:23:24,833 domogik-hue DEBUG Send client status : starting
2017-01-14 20:23:39,672 domogik-hue DEBUG Process informations|python_version=2.7|psutil_version=2.1.1|domogik_version=0.5.1|component=plugin-hue|component_version=1.0|pid=3314|cpu_percent_usage=0.2|memory_total=3693.0|memory_percent_usage=0.5|memory_rss=19.0|memory_vsz=402.0|num_threads=5|num_file_descriptors_used=19|platform=x86_64|num_core=2|git_branch=|git_revision=
2017-01-14 20:23:39,834 domogik-hue DEBUG Send client status : starting
2017-01-14 20:23:54,835 domogik-hue DEBUG Send client status : starting
2017-01-14 20:24:09,837 domogik-hue DEBUG Send client status : starting
2017-01-14 20:24:24,838 domogik-hue DEBUG Send client status : starting
2017-01-14 20:24:39,675 domogik-hue DEBUG Process informations|python_version=2.7|psutil_version=2.1.1|domogik_version=0.5.1|component=plugin-hue|component_version=1.0|pid=3314|cpu_percent_usage=0.2|memory_total=3693.0|memory_percent_usage=0.5|memory_rss=19.0|memory_vsz=402.0|num_threads=5|num_file_descriptors_used=19|platform=x86_64|num_core=2|git_branch=|git_revision=
2017-01-14 20:24:39,839 domogik-hue DEBUG Send client status : starting
2017-01-14 20:24:54,841 domogik-hue DEBUG Send client status : starting
2017-01-14 20:25:09,842 domogik-hue DEBUG Send client status : starting
2017-01-14 20:25:24,843 domogik-hue DEBUG Send client status : starting
2017-01-14 20:25:39,678 domogik-hue DEBUG Process informations|python_version=2.7|psutil_version=2.1.1|domogik_version=0.5.1|component=plugin-hue|component_version=1.0|pid=3314|cpu_percent_usage=0.2|memory_total=3693.0|memory_percent_usage=0.5|memory_rss=19.0|memory_vsz=402.0|num_threads=5|num_file_descriptors_used=19|platform=x86_64|num_core=2|git_branch=|git_revision=
2017-01-14 20:25:39,844 domogik-hue DEBUG Send client status : starting
2017-01-14 20:25:54,845 domogik-hue DEBUG Send client status : starting
2017-01-14 20:26:09,847 domogik-hue DEBUG Send client status : starting
2017-01-14 20:26:24,848 domogik-hue DEBUG Send client status : starting
2017-01-14 20:26:39,681 domogik-hue DEBUG Process informations|python_version=2.7|psutil_version=2.1.1|domogik_version=0.5.1|component=plugin-hue|component_version=1.0|pid=3314|cpu_percent_usage=0.2|memory_total=3693.0|memory_percent_usage=0.5|memory_rss=19.0|memory_vsz=402.0|num_threads=5|num_file_descriptors_used=19|platform=x86_64|num_core=2|git_branch=|git_revision=
2017-01-14 20:26:39,849 domogik-hue DEBUG Send client status : starting
2017-01-14 20:26:54,850 domogik-hue DEBUG Send client status : starting
2017-01-14 20:27:09,851 domogik-hue DEBUG Send client status : starting
2017-01-14 20:27:19,713 domogik-hue DEBUG Delete the file /var/run/domogik//hue_return_code_3295
2017-01-14 20:27:19,715 domogik-hue DEBUG __del__ Single client
2017-01-14 20:27:19,716 domogik-hue DEBUG force_leave called
2017-01-14 20:47:24,283 domogik-hue INFO Looking for launched instances of 'hue'
2017-01-14 20:47:24,321 domogik-hue INFO No existing process.
2017-01-14 20:47:24,328 domogik-hue INFO Starting the plugin in background...
2017-01-14 20:47:24,869 domogik-hue INFO Daemonize plugin hue
2017-01-14 20:47:24,871 domogik-hue DEBUG watcher fork
2017-01-14 20:47:24,872 domogik-hue INFO ----------------------------------
2017-01-14 20:47:24,874 domogik-hue INFO Starting client 'hue' (new manager instance)
2017-01-14 20:47:24,875 domogik-hue INFO Python version is sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)
2017-01-14 20:47:24,883 domogik-hue DEBUG Send client status : starting
2017-01-14 20:47:24,891 domogik-hue DEBUG Write pid file for pid '4102' in file '/var/run/domogik/hue.pid'
2017-01-14 20:47:24,892 domogik-hue DEBUG Send client status : starting
2017-01-14 20:47:24,893 domogik-hue INFO Read the json file and validate id
2017-01-14 20:47:24,901 domogik-hue INFO The json file is valid
2017-01-14 20:47:24,922 domogik-hue INFO Check if there are pictures for the defined products
2017-01-14 20:47:24,923 domogik-hue INFO There is no products defined for this client
2017-01-14 20:47:24,923 domogik-hue INFO End init of the global client part
2017-01-14 20:47:24,923 domogik-hue INFO Retrieve the devices list for this client...
2017-01-14 20:47:24,929 domogik-hue DEBUG Process informations|python_version=2.7|psutil_version=2.1.1|domogik_version=0.5.1|component=plugin-hue|component_version=1.0|pid=4102|cpu_percent_usage=0.0|memory_total=3693.0|memory_percent_usage=0.5|memory_rss=19.0|memory_vsz=338.0|num_threads=5|num_file_descriptors_used=19|platform=x86_64|num_core=2|git_branch=|git_revision=
2017-01-14 20:47:24,940 domogik-hue WARNING There is no device created for this client
2017-01-14 20:47:24,941 domogik-hue WARNING The developper requested to stop the client if there is no device created
2017-01-14 20:47:24,941 domogik-hue DEBUG force_leave called
2017-01-14 20:47:24,941 domogik-hue DEBUG Send client status : stopped
2017-01-14 20:47:24,942 domogik-hue INFO The thread send_status_loop was not registered, killing it
2017-01-14 20:47:24,958 domogik-hue INFO Thread send_status_loop stopped.
2017-01-14 20:47:24,958 domogik-hue INFO The thread send_process_info was not registered, killing it
2017-01-14 20:47:24,959 domogik-hue INFO Thread send_process_info stopped.
2017-01-14 20:47:24,959 domogik-hue INFO ==> commands:   {}
2017-01-14 20:47:24,960 domogik-hue INFO ==> sensors:   {}
2017-01-14 20:47:24,961 domogik-hue DEBUG Init config query(mq) instance
2017-01-14 20:47:24,964 domogik-hue INFO Request query config for client hue : key ip_bridge
2017-01-14 20:47:24,987 domogik-hue DEBUG Query config : successfull response : <MQMessage(action=config.result, data='{u'status': True, u'name': u'hue', u'reason': u'', u'value': u'192.168.1.2', u'host': u'debian', u'key': u'ip_bridge', u'type': u'plugin'}')>
2017-01-14 20:47:24,988 domogik-hue INFO Value for 'ip_bridge' is : 192.168.1.2
2017-01-14 20:47:24,988 domogik-hue INFO Casting value for key 'ip_bridge' in type 'string'...
2017-01-14 20:47:24,988 domogik-hue INFO Value is : 192.168.1.2
2017-01-14 20:47:25,006 domogik-hue ERROR Traceback (most recent call last):
  File "/var/lib/domogik//domogik_packages/plugin_hue/bin/hue.py", line 72, in __init__
    b = Bridge(self.get_config("ip_bridge"))
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 629, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 753, in connect
    self.register_app()
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 711, in register_app
    with open(self.config_file_path, 'w') as f:
IOError: [Errno 13] Permission denied: '/.python_hue'

2017-01-14 20:47:25,053 domogik-hue DEBUG Delete the file /var/run/domogik//hue_return_code_4081
2017-01-14 20:47:25,054 domogik-hue DEBUG __del__ Single client
2017-01-14 20:47:25,055 domogik-hue DEBUG force_leave called
2017-01-14 20:47:34,512 domogik-hue INFO Looking for launched instances of 'hue'
2017-01-14 20:47:34,549 domogik-hue INFO No existing process.
2017-01-14 20:47:34,556 domogik-hue INFO Starting the plugin in background...
2017-01-14 20:47:35,111 domogik-hue INFO Daemonize plugin hue
2017-01-14 20:47:35,114 domogik-hue DEBUG watcher fork
2017-01-14 20:47:35,115 domogik-hue INFO ----------------------------------
2017-01-14 20:47:35,117 domogik-hue INFO Starting client 'hue' (new manager instance)
2017-01-14 20:47:35,117 domogik-hue INFO Python version is sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)
2017-01-14 20:47:35,124 domogik-hue DEBUG Send client status : starting
2017-01-14 20:47:35,132 domogik-hue DEBUG Write pid file for pid '4146' in file '/var/run/domogik/hue.pid'
2017-01-14 20:47:35,132 domogik-hue INFO Read the json file and validate id
2017-01-14 20:47:35,135 domogik-hue DEBUG Send client status : starting
2017-01-14 20:47:35,141 domogik-hue INFO The json file is valid
2017-01-14 20:47:35,161 domogik-hue INFO Check if there are pictures for the defined products
2017-01-14 20:47:35,162 domogik-hue INFO There is no products defined for this client
2017-01-14 20:47:35,162 domogik-hue INFO End init of the global client part
2017-01-14 20:47:35,163 domogik-hue INFO Retrieve the devices list for this client...
2017-01-14 20:47:35,168 domogik-hue DEBUG Process informations|python_version=2.7|psutil_version=2.1.1|domogik_version=0.5.1|component=plugin-hue|component_version=1.0|pid=4146|cpu_percent_usage=0.0|memory_total=3693.0|memory_percent_usage=0.5|memory_rss=19.0|memory_vsz=338.0|num_threads=5|num_file_descriptors_used=19|platform=x86_64|num_core=2|git_branch=|git_revision=
2017-01-14 20:47:35,181 domogik-hue WARNING There is no device created for this client
2017-01-14 20:47:35,182 domogik-hue WARNING The developper requested to stop the client if there is no device created
2017-01-14 20:47:35,182 domogik-hue DEBUG force_leave called
2017-01-14 20:47:35,183 domogik-hue DEBUG Send client status : stopped
2017-01-14 20:47:35,183 domogik-hue INFO The thread send_status_loop was not registered, killing it
2017-01-14 20:47:35,202 domogik-hue INFO Thread send_status_loop stopped.
2017-01-14 20:47:35,203 domogik-hue INFO The thread send_process_info was not registered, killing it
2017-01-14 20:47:35,203 domogik-hue INFO Thread send_process_info stopped.
2017-01-14 20:47:35,204 domogik-hue INFO ==> commands:   {}
2017-01-14 20:47:35,205 domogik-hue INFO ==> sensors:   {}
2017-01-14 20:47:35,206 domogik-hue DEBUG Init config query(mq) instance
2017-01-14 20:47:35,208 domogik-hue INFO Request query config for client hue : key ip_bridge
2017-01-14 20:47:35,233 domogik-hue DEBUG Query config : successfull response : <MQMessage(action=config.result, data='{u'status': True, u'name': u'hue', u'reason': u'', u'value': u'192.168.1.2', u'host': u'debian', u'key': u'ip_bridge', u'type': u'plugin'}')>
2017-01-14 20:47:35,234 domogik-hue INFO Value for 'ip_bridge' is : 192.168.1.2
2017-01-14 20:47:35,234 domogik-hue INFO Casting value for key 'ip_bridge' in type 'string'...
2017-01-14 20:47:35,235 domogik-hue INFO Value is : 192.168.1.2
2017-01-14 20:47:35,253 domogik-hue ERROR Traceback (most recent call last):
  File "/var/lib/domogik//domogik_packages/plugin_hue/bin/hue.py", line 72, in __init__
    b = Bridge(self.get_config("ip_bridge"))
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 629, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 753, in connect
    self.register_app()
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 721, in register_app
    'The link button has not been pressed in the last 30 seconds.')
PhueRegistrationException

2017-01-14 20:47:35,305 domogik-hue DEBUG Delete the file /var/run/domogik//hue_return_code_4127
2017-01-14 20:47:35,306 domogik-hue DEBUG __del__ Single client
2017-01-14 20:47:35,307 domogik-hue DEBUG force_leave called

**Comment by overload08** [comment]
Added config directory propriety + chown -R domogik /var/lib/domogik/domogik_packages/plugin_hue
